### ISSUE TITLE
Dragging the top and left sides will change the opposite side.

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/vue-resizables#2]
Appearance:
 - Dragging the top and left sides will change the opposite side.

Expected:
 - Should the sides close to the element boundary need to be disabled? Maybe a prop whose default value is false to match common sense?

**Comment by alexzhang1030** [comment]
Agree with you. Now users need to define which edge can be dragged to resize. See -> [docs](https://vue-resizables.vercel.app/directives/#options)
