### ISSUE TITLE
The children of <Resizable /> should be a single element which seems different to the directive.

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/vue-resizables#4]
The <Resizable /> can be the single element.

**Comment by LoTwT** [comment]
I try the multiple elements in the playground using `<Resizable />`. It works great for me.
So why the doc says `The children of `Resizable` should always be a single element`?

**Comment by alexzhang1030** [comment]
Hmm, it's more like a `wrapper`. They add this component to what they want to resize.
If there are multiple elements, the bounding will be incorrect.
