### ISSUE TITLE
Zoom breaking the component

### ISSUE THREAD

**Issue by linspw** [alexzhang1030/vue-resizables#46]
Is there any way to pass a scale value to divide when calculating position values?
This is especially good in a zoom context

[screen-capture (6).webm](https://github.com/alexzhang1030/vue-resizables/assets/43552865/96fc0c76-7693-46e2-a7f7-1a9b46c6bec3)

**Comment by alexzhang1030** [comment]
Thanks for your feedback, I will investigate the solution soon.

**Comment by alexzhang1030** [comment]
And can you share your Zoom logic? That will help me to find the root cause.

**Comment by linspw** [comment]
Thank you very much for answering me

The use case is quite large due to the number of components it involves, I apologize I won't be able to go through everything


But a simplified way:
```vue
<template>
  <div class="canvas-zone">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { usePanel } from '../composables'

const panel = usePanel()

const transformStyle = computed(
  () =>
    `translate(${panel.canvasTranslate.x}px, ${panel.canvasTranslate.y}px) scale(${panel.currentZoom})`,
)
</script>

<style lang="scss">
 .canvas-zone {
  contain: layout style size;
  transform: v-bind('transformStyle');
  pointer-events: none;
  transform-origin: 0 0;
}
</style>

```

The resizable intem go inside this component, in the end of the day, is a css transform `scale(${.panel.currentZoom})`

**Comment by linspw** [comment]
I created a PR with the sugested solution:

https://github.com/alexzhang1030/vue-resizables/pull/47
