### ISSUE TITLE
Why the `import 'vue-resizables/style'` is necessary for using the borders.

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/vue-resizables#6]
After removing the `import 'vue-resizables/style'` in the playground and changing the border color and the border size, it works well.
I also tried force refresh, and it is the same.
Why the `import 'vue-resizables/style'` is necessary?

**Comment by alexzhang1030** [comment]
Because we use `unocss` for styling, the runtime added `unocss` shortcuts are invalid (won't compile to CSS).
So we need to import this style file.
